### ISSUE TITLE
SRS Introduction 

### ISSUE THREAD

**Issue by John0T** [Intro-to-SE-Lab-Fall-21-Section-2/Group-2#1]
need to fill out and complete information in part 1 of the SRS: Introduction

**Comment by ABux47** [comment]
For our introduction, we made sure to document the basic information regarding our program that we have accumulated thus far. This included information such as:

- Our goal for the program
- Waterdog Email's current version as of the writing of the SRS
- The typographical conventions used in the SRS
- A short product scope the detailing the programs  purpose, benefits and objectives
