### ISSUE TITLE
SRS-2 Overall Description

### ISSUE THREAD

**Issue by John0T** [Intro-to-SE-Lab-Fall-21-Section-2/Group-2#2]
Fill in and complete information in SRS part 2: Overall Description

**Comment by ABux47** [comment]
Question regarding 2.3 classes and user functionality?

**Comment by John0T** [comment]
> Question regarding 2.3 classes and user functionality?

no

**Comment by John0T** [comment]
- Properly Described the context in which the program will be designed in
- described the functions contained within the program
- designed the different users capable of accessing the program and their capabilities
- described the design and implementation constrains associated with this project
