### ISSUE TITLE
SRS-3 System Features

### ISSUE THREAD

**Issue by John0T** [Intro-to-SE-Lab-Fall-21-Section-2/Group-2#3]
Complete part 3 of the SRs: System Features.

**Comment by ABux47** [comment]
For section 3, System Features,  we reviewed the project topic pdf. Taking these guidelines into account, we have begun structuring our email client and planning out the essential features we would like to include. By the end of the semester,  we are hoping to have features including:
- Some form of access credentials
- A method of composing emails and saving drafts
- An inbox format to allow user to view their emails and search for specific files
- The ability to include and send attachments
